# 数组创建、索引与切片：精准取数的 N 种姿势

> 这是「数据分析从入门到精通」系列的第 3 篇。上一篇搞清楚了 NumPy 为什么快，这篇来解决一个更实际的问题——数组创建好了之后，怎么把我想要的那部分**精准捞出来**？

---

嗨，我是小荷。

没错，就是跟西汉开国名相萧何同音的那个「荷」——我可是萧丞相当年的头号粉丝。你要问我为什么一个搞数据的会迷历史人物？因为萧何干的事，本质上就是数据分析师的本职工作啊：管粮草、理账目、做人才盘点，全靠**精准的数据管理**。没有萧丞相，刘邦的仗根本打不下去。

所以今天咱们聊的这个主题——从数组里精准取数——我觉得萧何应该也会很感兴趣。毕竟在数据量大的情况下，**能不能快速、准确地找到你需要的那部分数据**，直接决定了你的工作效率。

上一篇我们跑了个实验，NumPy 比 Python 列表快 100 倍，你应该已经被震撼到了（没有的话可以回去再看一眼哈哈）。

但光会创建数组还不够，真正做数据分析，更多时间是在做这件事：

> 这 10 万行数据，我只想要第 3 列；这 5000 个用户，我只看 60 分以上的；这个矩阵，我需要左上角那个 3×3 的块……

**从数组里精准取数，就是今天要搞定的事。**

---

## 先搞定数组创建：6 种你必须会的方式

取数之前，先把数组创好。除了上一篇提到的 `np.array()`，还有几个超级常用的创建函数，一次说清楚：

In [2]:
import numpy as np

# 1. 从列表/嵌套列表创建（最基础）
a = np.array([10, 20, 30, 40, 50])
b = np.array([[1, 2, 3], [4, 5, 6]])   # 2D 数组

a, b

(array([10, 20, 30, 40, 50]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [3]:
# 2. arange：整数等差序列（用法像 range）
np.arange(1, 10, 2)        # [1 3 5 7 9]，步长 2

array([1, 3, 5, 7, 9])

In [4]:
# 3. linspace：指定个数的等间距序列（做图常用）
np.linspace(0, 1, 6)       # [0.  0.2  0.4  0.6  0.8  1. ]

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [5]:
# 4. zeros / ones：全零、全一（初始化矩阵必备）
np.zeros((3, 4))            # 3行4列，全是 0.0
np.ones((2, 3))             # 2行3列，全是 1.0

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
# 5. eye：单位矩阵（线性代数里会用到）
np.eye(3)                   # 3×3 对角线全是 1 的矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
# 6. random 系列：随机数组
np.random.randint(0, 100, size=(4, 5))   # 随机整数矩阵
np.random.randn(3, 3)                     # 标准正态分布

array([[ 1.06611658, -1.07868986, -1.47075733],
       [ 0.29907445,  0.87878208, -0.20860658],
       [ 1.25232791,  0.91099123, -0.70356782]])

> 小技巧：不确定自己数组长什么样，随时 `print(a.shape, a.dtype)` 确认一下，省得后面报错找半天。萧何管粮草也得先盘点库存嘛，我们也一样。

---

## 一维数组索引：和 Python 列表一样，但更好用

一维数组的索引规则和 Python 列表完全一致，正索引从 0 开始，负索引从 -1 开始：

In [8]:
scores = np.array([72, 85, 91, 63, 78, 88, 55, 96])

print(scores[0])    # 72，第一个
print(scores[-1])     # 96，最后一个
print(scores[-2])   # 55，倒数第二个


72
96
55


**切片：取一段**

In [9]:
scores[2:5]    # [91 63 78]，索引 2、3、4（不含 5）

array([91, 63, 78])

In [10]:
scores[:3]     # [72 85 91]，前 3 个

array([72, 85, 91])

In [11]:
scores[4:]     # [78 88 55 96]，从第 5 个到末尾

array([78, 88, 55, 96])

In [12]:
scores[::2]    # [72 91 78 55]，每隔一个取一个

array([72, 91, 78, 55])

In [13]:
scores[::-1]   # [96 55 88 78 63 91 85 72]，反转！

array([96, 55, 88, 78, 63, 91, 85, 72])

记不住？就记这个模板：`[start : stop : step]`，不写就是默认值。

---

## 二维数组索引：行列都要指定

二维数组就像 Excel 表格，要同时指定**行和列**。

In [14]:
# 模拟一份成绩表：5个同学，3门课（语文、数学、英语）
scores = np.array([
    [88, 92, 85],
    [76, 68, 90],
    [95, 87, 78],
    [60, 75, 82],
    [91, 83, 94]
])

# 取单个元素：[行, 列]
scores[0, 1]      # 92，第1个同学的数学成绩

np.int64(92)

In [15]:
# 取整行
scores[2]         # [95 87 78]，第3个同学所有科目

array([95, 87, 78])

In [16]:
scores[1:3]       # 第2、3个同学的所有科目

array([[76, 68, 90],
       [95, 87, 78]])

In [17]:
# 取整列
scores[:, 0]      # [88 76 95 60 91]，所有同学的语文成绩

array([88, 76, 95, 60, 91])

In [18]:
scores[:, 1:]     # 所有同学的数学+英语成绩

array([[92, 85],
       [68, 90],
       [87, 78],
       [75, 82],
       [83, 94]])

In [19]:
# 取子矩阵：前3个同学，后2门课
scores[:3, 1:]
# [[92 85]
#  [68 90]
#  [87 78]]

array([[92, 85],
       [68, 90],
       [87, 78]])

> 记住这个「逗号规则」：逗号左边管行，逗号右边管列。`scores[行切片, 列切片]`，写顺了之后超自然。

---

## 布尔索引：按条件筛数据（这个超级好用！）

这是 NumPy 索引里我最喜欢的一个功能，写法优雅，效率极高。

**场景：找出所有成绩不及格的同学**

In [21]:
math_scores = np.array([92, 68, 87, 75, 83])

# 先生成一个布尔数组
mask = math_scores < 75
print(mask)   # [False  True False  True False]

# 用布尔数组做索引，自动筛出满足条件的值
math_scores[mask]   # [68 75]

[False  True False False False]


array([68])

In [22]:
# 或者直接写在一起：
math_scores[math_scores < 75]   # [68 75]

array([68])

**多条件组合也没问题**

In [23]:
# 找出数学 70~90 分之间的成绩（注意用 & 不是 and）
math_scores[(math_scores >= 70) & (math_scores <= 90)]
# [75 83]

array([87, 75, 83])

In [24]:
# 找出不及格 或 满分 的成绩
math_scores[(math_scores < 60) | (math_scores == 100)]

array([], dtype=int64)

> ⚠️ 小陷阱：NumPy 的多条件要用 `&`（与）和 `|`（或），**不能用 Python 的 `and` / `or`**，否则会报错！每次踩这个坑的人不在少数，提前记住。这个坑就跟韩信当年抱怨萧何不给他举荐一样——人家萧何不是不举荐，是时机没到啊哈哈，你得先搞清楚规则。

---

## 花式索引：想取哪几个就取哪几个

除了连续切片，NumPy 还支持直接传入**索引列表**，随机取你指定的位置：

In [25]:
scores = np.array([72, 85, 91, 63, 78, 88, 55, 96])

# 取第 1、3、5 个（索引 0、2、4）
scores[[0, 2, 4]]      # [72 91 78]

array([72, 91, 78])

In [26]:
# 二维数组取指定几行
matrix = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
matrix[[0, 2]]         # 取第1行和第3行
# [[1 2 3]
#  [7 8 9]]

array([[1, 2, 3],
       [7, 8, 9]])

---

## 实战：用索引分析成绩表

把上面学的串起来，做一个完整的小分析：

In [27]:
import numpy as np

# 5个同学，语文/数学/英语 成绩
scores = np.array([
    [88, 92, 85],
    [76, 68, 90],
    [95, 87, 78],
    [60, 75, 82],
    [91, 83, 94]
])

# 1. 每个同学的总分
total = scores.sum(axis=1)
print("各同学总分：", total)
# [265 234 260 217 268]

各同学总分： [265 234 260 217 268]


In [28]:
# 2. 数学不及格（<75）的同学是第几号？
math = scores[:, 1]
fail_idx = np.where(math < 75)[0]
print("数学不及格的同学编号：", fail_idx + 1)   # +1 转成1-based
# [2 4]

数学不及格的同学编号： [2]


In [29]:
# 3. 提取数学不及格同学的全部成绩
print("不及格同学详细成绩：\n", scores[fail_idx])
# [[76 68 90]
#  [60 75 82]]

不及格同学详细成绩：
 [[76 68 90]]


In [ ]:
# 4. 每门课的平均分
avg = scores.mean(axis=0)
print(f"语文均分: {avg[0]:.1f}, 数学均分: {avg[1]:.1f}, 英语均分: {avg[2]:.1f}")
# 语文均分: 82.0, 数学均分: 81.0, 英语均分: 85.8

看到了吗？全程没有一行 for 循环，代码又短又快，这就是 NumPy 索引的魅力。萧何当年管理大汉的粮草账目，要是有 NumPy，估计能省出一半时间来帮刘邦下棋。

---

## 本篇小结

| 方法 | 语法 | 用途 |
|------|------|------|
| 普通索引 | `a[2]` / `a[-1]` | 取单个元素 |
| 切片 | `a[1:4]` / `a[::2]` | 取连续区间 |
| 二维索引 | `a[行, 列]` | 精准定位行列 |
| 布尔索引 | `a[a > 80]` | 按条件筛选 |
| 花式索引 | `a[[0, 2, 4]]` | 取任意指定位置 |

这几种方式在后面学 Pandas 的时候都会反复出现，现在把它们练熟，后面会省很多力气。

---

## 课后练习

用下面这个数组，完成 3 个小任务：

In [30]:
import numpy as np
np.random.seed(42)
data = np.random.randint(50, 100, size=(6, 4))
print(data)


[[88 78 64 92]
 [57 70 88 68]
 [72 60 60 73]
 [85 89 73 52]
 [71 51 73 93]
 [79 87 51 70]]


1. 取出第 2 行到第 4 行，第 2 列到第 3 列（共 3 行 2 列）
2. 找出第 1 列中所有大于 80 的值
3. 计算每行的最大值和每列的最小值

In [34]:
data[1:5,1:3] # 取出第 2 行到第 4 行，第 2 列到第 3 列（共 3 行 2 列）

array([[70, 88],
       [60, 60],
       [89, 73],
       [51, 73]])

In [35]:
data[data>80] # 找出第 1 列中所有大于 80 的值

array([88, 92, 88, 85, 89, 93, 87])

In [37]:
# 计算每行的最大值和每列的最小值
data.max(axis=1) # 每行的最大值

array([57, 51, 51, 52])

In [38]:
data.min(axis=0) # 每列的最小值

array([57, 51, 51, 52])

把你的代码和结果截图扔评论区，我看 👀

本篇完整代码包括练习题解答都已经上传至 GitHub 仓库，欢迎 Clone。

---

## 下期预告

> **第 4 篇：数组运算与广播机制**
>
> 两个形状不一样的数组，能直接相加吗？能。NumPy 的广播机制会自动帮你"对齐"——下篇用**批量标准化班级成绩**的场景，把这个有点抽象的概念讲到你一眼就懂。

---

**学到这里感觉还跟得上？**

👇 点「在看」，帮我推给更多想学数据的人  
💬 评论区写下你卡住的地方，我看到会回  
⭐ 关注公众号，更新不断，节奏稳定

---

*「数据分析从入门到精通」系列 · 第 3 篇*  
*上一篇：[第 2 篇：NumPy 快速入门：数组是什么，为什么快？]*  
*下一篇：第 4 篇：数组运算与广播机制*